[package]
name = "parser"
version = "0.1.0"
authors = ["TatriX <tatrics@gmail.com>"]

[dependencies]
hyper = "0.11.15"
futures = "0.1.18"
tokio-core = "0.1.12"
hyper-tls = "0.1.2"

[dev-dependencies]
mockito = "0.9.0"
